networks:
  fastapi_network:
    driver: bridge

volumes:
  fastapi_volume:

services:
  db:
    image: postgres:17.4-alpine3.21
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    env_file:
      - .env
    networks:
      - fastapi_network
    volumes:
      - fastapi_volume:/var/lib/postgresql/data
  api:
    build: .
    container_name: api
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - fastapi_network