networks:
  my_network:
    driver: bridge


volumes:
  db_data:

services:

  db:
    build:
      context: "./database/"
      dockerfile: Dockerfile
    container_name: db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - my_network

  api:
    build: .
    container_name: api
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - my_network