ERROR_REQUIRED_FIELD_NAME = "Nome é obrigatório"
ERROR_REQUIRED_FIELD_EMAIL = "Email é obrigatório"
ERROR_REQUIRED_FIELD_PHONE = "Número de telefone é obrigatório"
ERROR_REQUIRED_FIELD_PASSWORD = "Senha é obrigatória"
ERROR_REQUIRED_FIELD_LEVEL = "Nível é obrigatório"
ERROR_REQUIRED_FIELD_CPF_CNPJ = "CPF ou CNPJ é obrigatório"
ERROR_REQUIRED_FIELD_PIX_KEY_TYPE = "Tipo de Pix Key é obrigatório"
ERROR_REQUIRED_FIELD_PIX_KEY = "Pix Key é obrigatório"


ERROR_INVALID_EMAIL = "Email inválido"
ERROR_INVALID_PHONE = "Número de telefone inválido"
ERROR_INVALID_CPF_CNPJ = "CPF ou CNPJ inválido"
ERROR_INVALID_PIX_KEY_TYPE = "Tipo de Pix Key inválido"
ERROR_INVALID_PIX_KEY = "Pix Key inválido"
ERROR_INVALID_LEVEL = "Nível inválido"